### ISSUE TITLE
size doesn't match error when run the train.py

### ISSUE THREAD

**Issue by lj107024** [Deeachain/Segmentation-pytorch#1]
sorry to disturb you, when i run train.py, it goes wrong, and i print the size of the two tensor, there are same, i can't find the resolution, how to solve it?
`*******        Begining traing          *******
***********************************************
Epoch 0/300:   0%|          | 0/909 [00:00<?, ?it/s]/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 415, in <module>
    train_model(args)
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 293, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 117, in train
    loss = criterion(output, labels)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yeluyue/dl/bottle_Segmentation/tools/loss.py", line 27, in forward
    return self.loss(outputs, targets)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 498, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 2047, in binary_cross_entropy
    new_size = _infer_size(target.size(), weight.size())
RuntimeError: The size of tensor a (512) must match the size of tensor b (2) at non-singleton dimension 2`

**Comment by lj107024** [comment]
i guess may be the label i generated was incorrect,and i solved the problem before, but i have another question as follows, Can i ask for your pytorch version?
Epoch 0/300:   0%|          | 0/909 [00:00<?, ?it/s, loss=939.66357, lr=0.00033]Traceback (most recent call last):
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 421, in <module>
    train_model(args)
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 296, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 131, in train
    loss.backward()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by Deeachain** [comment]
My operating environment is show in requirement.txt ,you can run with pip install -r requirement.txt

**Comment by Deeachain** [comment]
> sorry to disturb you, when i run train.py, it goes wrong, and i print the size of the two tensor, there are same, i can't find the resolution, how to solve it?
> `******* Begining traing *******
> 
> Epoch 0/300: 0%| | 0/909 [00:00<?, ?it/s]/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
> warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
> Traceback (most recent call last):
> File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 415, in
> train_model(args)
> File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 293, in train_model
> lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
> File "/home/yeluyue/dl/bottle_Segmentation/train.py", line 117, in train
> loss = criterion(output, labels)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/yeluyue/dl/bottle_Segmentation/tools/loss.py", line 27, in forward
> return self.loss(outputs, targets)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 498, in forward
> return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 2047, in binary_cross_entropy
> new_size = _infer_size(target.size(), weight.size())
> RuntimeError: The size of tensor a (512) must match the size of tensor b (2) at non-singleton dimension 2`

loss = criterion(output, labels)
output.size is (n_classes, h, w)
labels.size is (h, w)
i guess you should use function torch.argmax(output, dim = 1) before loss = criterion(output, labels) while you  use binary_cross_entropy.

**Comment by lj107024** [comment]
thank you！
