### ISSUE TITLE
AttributeError in HRNet

### ISSUE THREAD

**Issue by rrryan2016** [Deeachain/Segmentation-Pytorch#10]
When I run `./model/HRNet.py` on Ubuntu 18.04, torch 1.8.0+cu111, the error raise as follows, 

> /home/vgc/users/lwz/code/rice_seg/template/Segmentation-Pytorch/model/HRNet.py:329: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   last_inp_channels = np.int(np.sum(pre_stage_channels))
> Traceback (most recent call last):
>   File "/home/vgc/users/lwz/code/rice_seg/template/Segmentation-Pytorch/model/HRNet.py", line 520, in <module>
>     summary(model, (3, 512, 512), device="cpu")
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
>     model(*x)
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/vgc/users/lwz/code/rice_seg/template/Segmentation-Pytorch/model/HRNet.py", line 447, in forward
>     y_list = self.stage2(x_list)
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
>     input = module(input)
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 893, in _call_impl
>     hook_result = hook(self, input, result)
>   File "/home/vgc/anaconda3/envs/lwz37/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 19, in hook
>     summary[m_key]["input_shape"] = list(input[0].size())
> AttributeError: 'list' object has no attribute 'size'

**Comment by CharlesPikachu** [comment]
maybe you can use this repo: https://github.com/SegmentationBLWX/sssegmentation

**Comment by Deeachain** [comment]
Hi,
Please check your numpy version with requirements.txt
