### ISSUE TITLE
你好，请问你用deeplabv3+网络训练的命令是什么？

### ISSUE THREAD

**Issue by wqangzuoshuai** [Deeachain/Segmentation-Pytorch#17]
谢谢大佬的代码。我想要使用deeplabv3+复现你的效果，我看见你的crop size为768，而base size也是768，这是为什么？请问您用deeplabv3+的训练命令是什么，可以告诉我吗？谢谢大佬

**Comment by Deeachain** [comment]
basesize可以自定义设定，表示基础读取图片大小；cropsize为数据增广时裁剪图片的尺寸，即模型的输入大小
修改train.sh中的--model参数即可训练deeplabv3+
