### ISSUE TITLE
使用ENet模型，在train时正常，在pridict时会出现超出内存。

### ISSUE THREAD

**Issue by FelixJiao** [Deeachain/Segmentation-Pytorch#2]
在train时正常，在pridict时会出现： 
RuntimeError.CUDA out of memory. Tried to allocate 188.00 MiB (GPU 0; 6.00 GiB total capacity; 4.21 GiB already allocated; 63.85 MiB free; 81.86 MiB cached)
使用predict_sliding时会出现：
发生异常: TypeError
__init__() got an unexpected keyword argument 'std'
请问怎么解决？

**Comment by Deeachain** [comment]
请问你是用的自己的数据集还是公开数据集？
第一个问题，看报错情况是显存不够了，首先需要确认一下，运行预测代码之前，显卡的显存是否充足；其次
![image](https://user-images.githubusercontent.com/58386037/98360693-3b15c400-2065-11eb-8d7e-e3be83b968f9.png)这两个切换一下试试，多试几次，我之前也遇到过类似情况
第二个问题，很明显是缺少了图片的方差值，加上你所计算的图片方差值，格式如下：（X1，X2，X3），其中X1、X2、X3为你的计算值

**Comment by FelixJiao** [comment]
![image](https://user-images.githubusercontent.com/33050328/98437103-b2595f80-211a-11eb-9e33-8806aee3926f.png)
在循环前加了一行代码，解决爆显存问题。
