### ISSUE TITLE
作者你好，关于在windows10平台上训练卡住的情况

### ISSUE THREAD

**Issue by sunanlin13174** [Deeachain/Segmentation-Pytorch#21]
我在windows10平台上训练cityspaces数据集，只有一块显卡，我注释掉了分布式加载模型代码。数据载入设置num_works=0训练，但是会在某个epoch结束后卡住，请问这可能是什么原因呢？

**Comment by Deeachain** [comment]
你只注释了分布式加载模型代码，是否使用了分布式训练呢，我猜测是不是windows不支持该方式
