### ISSUE TITLE
事实证明，训练不了

### ISSUE THREAD

**Issue by anmochen** [Deeachain/Segmentation-Pytorch#24]

**Comment by Deeachain** [comment]
首先，代码是开源工作，我调试通过后上传（存在bug或者其他问题也是难免的，但不可能不能跑通）；其次，如果代码有运行异常报错问题，可以附上报错截图一起讨论，而您直接对代码下了一个结论“事实证明，训练不了”，个人认为您好像不配作出如此否定的评价；最后，或许您觉得一句“事实证明，训练不了”能够抒发你对本仓库代码的不屑之意，但您是否能想过是自己的能力问题，连别人写好的代码都无法正常跑通呢？我个人认为你可能不太适合开展深度学习的科研工作，没有谦卑的心态却在学术讨论的地方指点江山。
