### ISSUE TITLE
请问有测试每个模型在citycaps 上的性能吗

### ISSUE THREAD

**Issue by xiexu666** [Deeachain/Segmentation-Pytorch#4]
有没有具体指标可以参考下

**Comment by Deeachain** [comment]
时间有限，没有对每个模型进行实验(后期会更新)。Readme中展示的DDRNet，基本能够复现论文指标。DDRNet引用：Hong Y, Pan H, Sun W, et al. Deep Dual-resolution Networks for Real-time and Accurate Semantic Segmentation of Road Scenes[J]. arXiv preprint arXiv:2101.06085, 2021.

**Comment by xiexu666** [comment]
> 
> 
> 时间有限，没有对每个模型进行实验(后期会更新)。Readme中展示的DDRNet，基本能够复现论文指标。DDRNet引用：Hong Y, Pan H, Sun W, et al. Deep Dual-resolution Networks for Real-time and Accurate Semantic Segmentation of Road Scenes[J]. arXiv preprint arXiv:2101.06085, 2021.

好的感谢回复
