### ISSUE TITLE
bug about generate_txt.py

### ISSUE THREAD

**Issue by songzijiang** [Deeachain/Segmentation-Pytorch#5]
in line 26
`filename_gt = filename.replace('leftImg8bit', 'gtFine')`
should change to 
`filename_gt = filename.replace('leftImg8bit', 'gtFine').replace('.png','_labelTrainIds.png')`
to produce the format of 
`leftImg8bit/train/cologne/cologne_000001_000019_leftImg8bit.png gtFine/train/cologne/cologne_000001_000019_gtFine_labelTrainIds.png`

the result will be 
`leftImg8bit/train/cologne/cologne_000001_000019_leftImg8bit.png gtFine/train/cologne/cologne_000001_000019_gtFine.png`
before. And the program won`t` find the file.

if I am wrong, plz tell me. Best wishes.

**Comment by Deeachain** [comment]
Thank you very much for pointing out the error in this code，and I have taken your suggestion to update `generate.txt`.  
Finally, we firmly believe that the following format is correct.
`
leftImg8bit/train/cologne/cologne_000001_000019_leftImg8bit.png gtFine/train/cologne/cologne_000001_000019_gtFine_labelTrainIds.png
`

**Comment by songzijiang** [comment]
Thanks for the work. I am trying to reproduce the scores. I will close this issue later.
