### ISSUE TITLE
Error when run train.sh

### ISSUE THREAD

**Issue by NguyenCongPhucBK** [Deeachain/Segmentation-Pytorch#7]
Hi,
I train model in Google Colab and i bug:
![image](https://user-images.githubusercontent.com/80568515/118233869-bd6fbc80-b4bc-11eb-8def-98b75352919f.png)
Can you help me?
Thanks you so much!

**Comment by NguyenCongPhucBK** [comment]
I installed package in requirements.txt, and I still bug in local server:
![Capture](https://user-images.githubusercontent.com/80568515/118234322-61596800-b4bd-11eb-8154-1bbca8030275.PNG)

**Comment by NguyenCongPhucBK** [comment]
I edit to fix bug:
![image](https://user-images.githubusercontent.com/80568515/118238552-d9765c80-b4c2-11eb-8298-725a3e8269f8.png)

But, i have other bug:

**Comment by NguyenCongPhucBK** [comment]
Can you help me, @Deeachain ?

**Comment by Deeachain** [comment]
Hi，
You annotated `trainLoader` and `testLoader`, It needs to be revised.
![image](https://user-images.githubusercontent.com/58386037/118289905-67c10180-b508-11eb-85f1-9e19aa031c54.png)

**Comment by NguyenCongPhucBK** [comment]
Thanks @Deeachain , I train successful!. I close Issuse. I hope DDRNet 23-slim coming soon! Thank you so much!

**Comment by Deeachain** [comment]
> I installed package in requirements.txt, and I still bug in local server:
> ![Capture](https://user-images.githubusercontent.com/80568515/118234322-61596800-b4bd-11eb-8154-1bbca8030275.PNG)
This is not a code bug, you should set the '--nproc_per_node=2' in 'train.sh' to the number of graphics cards when the number of your lab devices changes (the default is dual cards)
